In [7]:
import numpy as np

image = [[abs(i - j) for j in range(8)] for i in range(8)]
image_array = np.array(image)

print(image_array)

[[0 1 2 3 4 5 6 7]
 [1 0 1 2 3 4 5 6]
 [2 1 0 1 2 3 4 5]
 [3 2 1 0 1 2 3 4]
 [4 3 2 1 0 1 2 3]
 [5 4 3 2 1 0 1 2]
 [6 5 4 3 2 1 0 1]
 [7 6 5 4 3 2 1 0]]
