In [23]:
import numpy as np

sigma = 1.4
mask = np.zeros((7, 7))

for x in range(-3, 4):
    for y in range(-3, 4):
        mask[x + 3, y + 3] = np.round(np.exp((-x * x - y * y) / (2 * sigma**2)), 4)

print(mask)

[[0.0101 0.0363 0.078  0.1007 0.078  0.0363 0.0101]
 [0.0363 0.1299 0.2793 0.3604 0.2793 0.1299 0.0363]
 [0.078  0.2793 0.6004 0.7748 0.6004 0.2793 0.078 ]
 [0.1007 0.3604 0.7748 1.     0.7748 0.3604 0.1007]
 [0.078  0.2793 0.6004 0.7748 0.6004 0.2793 0.078 ]
 [0.0363 0.1299 0.2793 0.3604 0.2793 0.1299 0.0363]
 [0.0101 0.0363 0.078  0.1007 0.078  0.0363 0.0101]]


In [33]:
min_value = np.min(mask)
normalized_mask = mask / min_value
normalized_mask_int = np.round(normalized_mask,0).astype(np.uint8)

print(normalized_mask_int)
print("1/K^2: ", "1/", np.sum(normalized_mask_int))

[[ 1  4  8 10  8  4  1]
 [ 4 13 28 36 28 13  4]
 [ 8 28 59 77 59 28  8]
 [10 36 77 99 77 36 10]
 [ 8 28 59 77 59 28  8]
 [ 4 13 28 36 28 13  4]
 [ 1  4  8 10  8  4  1]]
1/K^2:  1/ 1203


In [35]:
a = [173, 130, 104, 62, 229, 52, 51, 63, 192, 199, 22, 189, 0, 0, 128, 63, 140, 157, 156, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 80, 28, 77, 62, 82, 117, 52, 63, 171, 81, 62, 188, 0, 0, 128, 63, 144, 158, 157, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 127, 211, 6, 62, 129, 149, 149, 63, 15, 34, 159, 189, 0, 0, 128, 63, 145, 157, 159, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 83, 232, 179, 61, 196, 251, 150, 63, 163, 109, 161, 189, 0, 0, 128, 63, 144, 157, 159, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 115, 213, 47, 61, 178, 76, 152, 63, 207, 142, 13, 189, 0, 0, 128, 63, 119, 137, 138, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 100, 243, 14, 187, 78, 199, 152, 63, 61, 136, 14, 189, 0, 0, 128, 63, 135, 155, 156, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 200, 159, 203, 189, 231, 192, 163, 63, 127, 196, 178, 189, 0, 0, 128, 63, 134, 154, 155, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 223, 255, 77, 189, 206, 169, 164, 63, 16, 243, 30, 189, 0, 0, 128, 63, 132, 152, 153, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 246, 27, 8, 190, 159, 212, 145, 63, 204, 80, 154, 189, 0, 0, 128, 63, 138, 158, 157, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 74, 182, 50, 190, 109, 224, 144, 63, 63, 207, 0, 189, 0, 0, 128, 63, 149, 167, 166, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 42, 164, 140, 190, 20, 4, 151, 63, 171, 86, 159, 189, 0, 0, 128, 63, 144, 161, 158, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 49, 249, 108, 190, 218, 187, 153, 63, 49, 44, 11, 189, 0, 0, 128, 63, 150, 167, 164, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 87, 39, 91, 62, 25, 101, 44, 63, 201, 148, 112, 60, 0, 0, 128, 63, 120, 130, 130, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 180, 108, 23, 62, 7, 208, 129, 63, 6, 86, 63, 60, 0, 0, 128, 63, 134, 146, 146, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 43, 72, 178, 61, 19, 128, 151, 63, 182, 73, 44, 60, 0, 0, 128, 63, 132, 145, 147, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 209, 191, 244, 61, 191, 6, 140, 63, 35, 87, 84, 61, 0, 0, 128, 63, 123, 132, 131, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 16, 119, 233, 186, 104, 159, 158, 63, 75, 94, 36, 60, 0, 0, 128, 63, 136, 156, 157, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 84, 137, 45, 61, 39, 88, 152, 63, 82, 111, 96, 61, 0, 0, 128, 63, 122, 142, 144, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 173, 82, 71, 189, 220, 160, 158, 63, 28, 231, 36, 60, 0, 0, 128, 63, 135, 155, 156, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 245, 70, 201, 189, 3, 53, 164, 63, 33, 5, 111, 61, 0, 0, 128, 63, 133, 153, 158, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 13, 73, 22, 190, 39, 78, 163, 63, 231, 214, 42, 60, 0, 0, 128, 63, 143, 164, 162, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 112, 139, 21, 190, 148, 55, 163, 63, 60, 85, 111, 61, 0, 0, 128, 63, 136, 156, 160, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 149, 172, 157, 190, 111, 206, 170, 63, 105, 30, 70, 60, 0, 0, 128, 63, 143, 160, 157, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 203, 112, 132, 190, 207, 93, 173, 63, 230, 106, 128, 61, 0, 0, 128, 63, 142, 164, 161, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 93, 198, 39, 62, 86, 219, 142, 63, 101, 238, 193, 61, 0, 0, 128, 63, 129, 130, 134, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 147, 128, 86, 62, 123, 92, 145, 63, 121, 144, 14, 62, 0, 0, 128, 63, 76, 66, 79, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 125, 216, 192, 61, 245, 224, 162, 63, 82, 129, 216, 61, 0, 0, 128, 63, 105, 117, 120, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 227, 15, 241, 61, 75, 76, 139, 63, 223, 55, 7, 62, 0, 0, 128, 63, 91, 87, 98, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 128, 169, 111, 186, 44, 15, 171, 63, 16, 155, 225, 61, 0, 0, 128, 63, 130, 152, 158, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 42, 153, 69, 189, 197, 49, 158, 63, 18, 225, 209, 61, 0, 0, 128, 63, 130, 153, 161, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 16, 67, 193, 189, 108, 186, 157, 63, 198, 196, 209, 61, 0, 0, 128, 63, 133, 155, 161, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 244, 172, 20, 190, 190, 227, 162, 63, 162, 255, 216, 61, 0, 0, 128, 63, 134, 156, 162, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 22, 25, 144, 190, 38, 73, 189, 63, 226, 23, 253, 61, 0, 0, 128, 63, 126, 148, 154, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0]

In [36]:
len(a)

1056

In [37]:
b = [36, 64, 50, 190, 10, 171, 193, 63, 90, 104, 69, 189, 0, 0, 128, 63, 150, 173, 173, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 218, 181, 161, 190, 163, 82, 209, 63, 246, 170, 86, 189, 0, 0, 128, 63, 152, 173, 171, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 217, 133, 49, 190, 94, 219, 193, 63, 160, 118, 32, 60, 0, 0, 128, 63, 150, 173, 175, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 15, 69, 107, 190, 28, 13, 192, 63, 72, 168, 41, 60, 0, 0, 128, 63, 152, 173, 174, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 163, 12, 161, 190, 184, 144, 209, 63, 193, 222, 48, 60, 0, 0, 128, 63, 151, 172, 172, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 201, 49, 152, 190, 115, 9, 199, 63, 51, 62, 144, 61, 0, 0, 128, 63, 151, 172, 171, 255, 127, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0]

In [38]:
len(b)

192